### PR TITLE
Conversion to SCSS

### PR DESCRIPTION
**Pull request by dimaursu**
#118 
The port took place initially from the diaspora/jsxc repo, there might be some differences.

### CODE REVIEW

**Comment by sualko** [comment]
I will remove those differences and merge afterwards. Thanks for your contribution.

**Comment by sualko** [comment]
Please checkout https://github.com/sualko/jsxc/compare/dimaursu:scss...sualko:dimaursu-scss

I think we should discuss two more topics:

- **variable names** Maybe we should not use color values as names, because if we change the value the name will not fit anymore.
- **generated files** I would like to put all generated files (css and js, see #121) to gitignore and use grunt-watch while developing.

**Comment by dimaursu** [comment]
I think I mentioned it in the issue. Yes, the color names should be definitely more generic, or semantic, not sure how to call them. Also, there are a few that are not yet extacted. 
One more thing - for the different shades of colors, it makes sense to use in some places the Sass functions `lighten` and `darken`, like so ->  `ligthten($color, 10%)`

**Comment by sualko** [comment]
I see <code>_colors</code> as a kind of config file and therefore I suggest we use functional names, like <code>$roster_bg</code> and align those variables "group color variables". e.g.

```
$color1: #xxx;

$roster_bg: $color1;
$chatwindow_bg: $color1;
```

Do you agree, or do you have a better solution?

**Comment by sualko** [comment]
colors

On this image you see, which colors I combined.

I also created a jsxc and webrtc module to be able to replace the color file in other projects.

**Pull request merged**
